### PR TITLE
Adding new Button example that demonstrates the new EV3Key implementation.

### PR DESCRIPTION
**Pull request by jartu**
(if accepted, a link to this could be added to the list of examples in ev3dev-lang-java/README.md file)

### CODE REVIEW

**Comment by jabrena** [comment]
Hi @jartu ,

I will test tomorrow, but I suppose that it will run nice. :)
Yes, of course, we will add in the README.md.

What do you like more?

* navigation
* computer-vision
* APIs
* ROS
* Algorithms

**Comment by jabrena** [comment]
Nice execution!!!

``` 
java -server -jar /home/robot/template_project_gradle-all-0.1.1.jar 
ev3dev#1|Registering key listeners...
ev3dev#1|Listener for UP key registered
ev3dev#1|Listener for DOWN key registered
ev3dev#1|Listener for ALL key registered
ev3dev#1|
ev3dev#1|Keep pressing any buttons to see listeners getting key press/release events.
ev3dev#1|Notice that if you press or release one of the [UP, DOWN] buttons, you'll get two events:
ev3dev#1|  1) one for the listener registered on that specific key
ev3dev#1|  2) another one for the listener registered on the special ALL key
ev3dev#1|
ev3dev#1|Press the ESCAPE key to terminate the program...
ev3dev#1|2017-07-12 19:21:49 [Thread-1] DEBUG ev3dev.sensors.EV3Key - KeyType UP pressed
ev3dev#1|19:21:51.103 - [UP listener] UP pressed
ev3dev#1|19:21:51.429 - [ALL listener] UP pressed
ev3dev#1|2017-07-12 19:21:51 [Thread-1] DEBUG ev3dev.sensors.EV3Key - KeyType UP released
ev3dev#1|19:21:51.518 - [UP listener] UP released
ev3dev#1|19:21:51.553 - [ALL listener] UP released
ev3dev#1|2017-07-12 19:21:55 [Thread-1] DEBUG ev3dev.sensors.EV3Key - KeyType DOWN pressed
ev3dev#1|19:21:55.703 - [DOWN listener] DOWN pressed
ev3dev#1|19:21:55.747 - [ALL listener] DOWN pressed
ev3dev#1|2017-07-12 19:21:55 [Thread-1] DEBUG ev3dev.sensors.EV3Key - KeyType DOWN released
ev3dev#1|19:21:55.935 - [DOWN listener] DOWN released
ev3dev#1|19:21:55.969 - [ALL listener] DOWN released
ev3dev#1|2017-07-12 19:21:57 [Thread-1] DEBUG ev3dev.sensors.EV3Key - KeyType LEFT pressed
ev3dev#1|19:21:57.722 - [ALL listener] LEFT pressed
ev3dev#1|2017-07-12 19:21:57 [Thread-1] DEBUG ev3dev.sensors.EV3Key - KeyType LEFT released
ev3dev#1|19:21:57.921 - [ALL listener] LEFT released
ev3dev#1|2017-07-12 19:22:10 [Thread-1] DEBUG ev3dev.sensors.EV3Key - KeyType UP pressed
ev3dev#1|19:22:10.525 - [UP listener] UP pressed
ev3dev#1|19:22:10.606 - [ALL listener] UP pressed
ev3dev#1|2017-07-12 19:22:10 [Thread-1] DEBUG ev3dev.sensors.EV3Key - KeyType UP released
ev3dev#1|19:22:10.703 - [UP listener] UP released
ev3dev#1|19:22:10.726 - [ALL listener] UP released
ev3dev#1|2017-07-12 19:22:16 [Thread-1] DEBUG ev3dev.sensors.EV3Key - KeyType DOWN pressed
ev3dev#1|19:22:16.244 - [DOWN listener] DOWN pressed
ev3dev#1|19:22:16.265 - [ALL listener] DOWN pressed
ev3dev#1|2017-07-12 19:22:16 [Thread-1] DEBUG ev3dev.sensors.EV3Key - KeyType DOWN released
ev3dev#1|19:22:16.419 - [DOWN listener] DOWN released
ev3dev#1|19:22:16.452 - [ALL listener] DOWN released
ev3dev#1|2017-07-12 19:22:18 [Thread-1] DEBUG ev3dev.sensors.EV3Key - KeyType LEFT pressed
ev3dev#1|19:22:18.653 - [ALL listener] LEFT pressed
ev3dev#1|2017-07-12 19:22:18 [Thread-1] DEBUG ev3dev.sensors.EV3Key - KeyType LEFT released
ev3dev#1|19:22:18.830 - [ALL listener] LEFT released
ev3dev#1|2017-07-12 19:22:24 [Thread-1] DEBUG ev3dev.sensors.EV3Key - KeyType LEFT pressed
ev3dev#1|19:22:24.914 - [ALL listener] LEFT pressed
ev3dev#1|2017-07-12 19:22:25 [Thread-1] DEBUG ev3dev.sensors.EV3Key - KeyType LEFT released
ev3dev#1|19:22:25.085 - [ALL listener] LEFT released
ev3dev#1|2017-07-12 19:22:26 [Thread-1] DEBUG ev3dev.sensors.EV3Key - KeyType RIGHT pressed
ev3dev#1|19:22:26.572 - [ALL listener] RIGHT pressed
ev3dev#1|2017-07-12 19:22:26 [Thread-1] DEBUG ev3dev.sensors.EV3Key - KeyType RIGHT released
ev3dev#1|19:22:26.760 - [ALL listener] RIGHT released
ev3dev#1|2017-07-12 19:22:28 [Thread-1] DEBUG ev3dev.sensors.EV3Key - KeyType UP pressed
ev3dev#1|19:22:28.414 - [UP listener] UP pressed
ev3dev#1|19:22:28.445 - [ALL listener] UP pressed
ev3dev#1|2017-07-12 19:22:28 [Thread-1] DEBUG ev3dev.sensors.EV3Key - KeyType UP released
ev3dev#1|19:22:28.610 - [UP listener] UP released
ev3dev#1|19:22:28.636 - [ALL listener] UP released
ev3dev#1|2017-07-12 19:22:29 [Thread-1] DEBUG ev3dev.sensors.EV3Key - KeyType DOWN pressed
ev3dev#1|19:22:29.744 - [DOWN listener] DOWN pressed
ev3dev#1|19:22:29.768 - [ALL listener] DOWN pressed
ev3dev#1|2017-07-12 19:22:29 [Thread-1] DEBUG ev3dev.sensors.EV3Key - KeyType DOWN released
ev3dev#1|19:22:29.942 - [DOWN listener] DOWN released
ev3dev#1|19:22:29.972 - [ALL listener] DOWN released
ev3dev#1|2017-07-12 19:22:31 [Thread-1] DEBUG ev3dev.sensors.EV3Key - KeyType ESCAPE pressed
ev3dev#1|19:22:31.674 - [ALL listener] ESCAPE pressed
ev3dev#1|
ev3dev#1|ESCAPE press detected, terminating the program.
ev3dev#1|2017-07-12 19:22:31 [Thread-1] DEBUG ev3dev.sensors.EV3Key - KeyType ESCAPE released
ev3dev#1|19:22:31.887
``` 

In the next review of examples I will add a verification to ensure that the example only run on EV3.

Merged.

**Comment by jabrena** [comment]
I have released a SNAPSHOT version with the new button support.
https://jitpack.io/#ev3dev-lang-java/ev3dev-lang-java/0.7.1-SNAPSHOT

**Comment by jartu** [comment]
Cool, thanks!
J.

**Comment by jabrena** [comment]
Review this class:
https://github.com/ev3dev-lang-java/ev3dev-lang-java/blob/develop/src/main/java/ev3dev/utils/Brickman.java

Maybe, it could be interesting for the example. It disable brickman in the startup to avoid mix interaction in the button example and a interaction with Brickman.

Cheers

Juan Antonio

**Comment by jartu** [comment]
I was looking for something like this. Thanks, I should definitely use this
for the button example.
J.

2017-07-13 0:17 GMT+02:00 Juan Antonio Breña Moral <notifications@github.com

**Comment by jabrena** [comment]
In the template, you I have just uploaded the new task to execute sudo operations.
https://github.com/ev3dev-lang-java/template_project_gradle/blob/master/deploy.gradle

To disable Brickman, it is necessary to execute the jar with root permissions. It is not ideal, but I didn't find another way.

https://www.youtube.com/watch?v=E2MV6_4um0A

**Pull request merged**
